# Everforest color palette
#272E33	user
#3b4252	dir
#434c5e	git
#4c566a	version
#5e81ac	doc (from dracula color palette)
#A7C080	time (from dracula color palette)

format = """
[░▒▓](#272E33)\
$os\
$username\
[](bg:#3b4252 fg:#272E33)\
$directory\
[](fg:#3b4252 bg:#434c5e)\
$git_branch\
$git_status\
[](fg:#434c5e bg:#4c566a)\
$c\
$python\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#4c566a bg:#D3C6AA)\
$docker_context\
[](fg:#D3C6AA bg:#A7C080)\
$time\
[ ](fg:#A7C080)\
\n
$cmd_duration\
$character\
"""
#add_newline = false

[line_break]
disabled = false

[username]
show_always = true
style_user = "bg:#272E33"
style_root = "bg:#9A348E"
format = '[󰣇 $user ]($style)'
disabled = false

[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#3b4252"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#5e81ac"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#434c5e"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:##434c5e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#A7C080 fg:#272E33"
format = '[  $time ]($style)'
	
[character]
success_symbol = '[ ➜](#A7C080)'
error_symbol = '[ ➜](bold red)'
#style = "bg:#A7C080"

[cmd_duration]
min_time = 500
format = ' [$duration](#A7C080)'