
[colors.primary]
background = '#080808'
foreground = '#E1E0D5'

[colors.cursor]
text = '#CCCABA'
cursor = '#E1E0D5'

# Normal colors
[colors.normal]
black   = '#080808'
red     = '#242322'
green   = '#484540'
yellow  = '#49473D'
blue    = '#4B4843'
magenta = '#6D6A58'
cyan    = '#7F7C65'
white   = '#CCCABA'

# Bright colors
[colors.bright]
black   = '#8F8D83'
red     = '#302F2D'
green   = '#605C56'
yellow  = '#615E51'
blue    = '#646059'
magenta = '#928D75'
cyan    = '#AAA587'
white   = '#CCCABA'
