
[colors.primary]
background = '#001514'
foreground = '#FEFBF4'

[colors.cursor]
text = '#F5F1E7'
cursor = '#FEFBF4'

# Normal colors
[colors.normal]
black   = '#001514'
red     = '#064C80'
green   = '#296C8A'
yellow  = '#4D8D93'
blue    = '#5F9D98'
magenta = '#BA935E'
cyan    = '#BDB7A7'
white   = '#F5F1E7'

# Bright colors
[colors.bright]
black   = '#ACA9A1'
red     = '#0865AB'
green   = '#3790B7'
yellow  = '#66BBC4'
blue    = '#7ED1CA'
magenta = '#F8C47E'
cyan    = '#FCF4DF'
white   = '#F5F1E7'
