
[colors.primary]
background = '#070809'
foreground = '#FBF6FA'

[colors.cursor]
text = '#F1EAEF'
cursor = '#FBF6FA'

# Normal colors
[colors.normal]
black   = '#070809'
red     = '#49142C'
green   = '#4F2E3F'
yellow  = '#89405F'
blue    = '#914363'
magenta = '#8E7379'
cyan    = '#B7ADB4'
white   = '#F1EAEF'

# Bright colors
[colors.bright]
black   = '#070809'
red     = '#49142C'
green   = '#4F2E3F'
yellow  = '#89405F'
blue    = '#914363'
magenta = '#8E7379'
cyan    = '#B7ADB4'
white   = '#F1EAEF'
